# Generated by Django 3.1 on 2020-09-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_auto_20200912_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_num',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
