# Generated by Django 3.1 on 2020-09-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20200912_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_num',
        ),
    ]
